helm_deploy/manage-recalls-api/values.yaml
helm_deploy/values-dev.yaml

This was given to us from the cloud platform team to be used so that
alerts are routed to us correctly...
ref:
- ministryofjustice/cloud-platform#2926 (comment)
- https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-prometheusrule

Set the `alertSeverity` value

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/search/PrisonerOffenderSearchClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/PrisonerSearchIntegrationTest.kt

Expect 'nomsNumber' for search, in place of 'name in request; 
Return 'prisonerNumber' as 'nomsNumber' in place of 'nomisNumber'; 
allow null name fields in search response.

[PUD-63][AN] API: align with UI re. 'nomsNumber' for search etc.

---

helm_deploy/manage-recalls-api/Chart.yaml
helm_deploy/manage-recalls-api/subcharts/gotenberg/.helmignore
helm_deploy/manage-recalls-api/subcharts/gotenberg/Chart.yaml
helm_deploy/manage-recalls-api/subcharts/gotenberg/templates/_helpers.tpl
helm_deploy/manage-recalls-api/subcharts/gotenberg/templates/deployment.yaml
helm_deploy/manage-recalls-api/subcharts/gotenberg/templates/service.yaml
helm_deploy/manage-recalls-api/subcharts/gotenberg/values.yaml

This installs gotenburg as a separate deployment/service within k8s 
so it  can be used by the API service (rather than a sidecar), but it will 
be deployed as part of the API service helm chart.
Gotenburg will be available internally (within the k8s namespace) at the following URL:
http://manage-recalls-api-gotenburg
(No need for a port as the service is listening on port 80).

PUD-107: Add gotenburg as a helm subchart

---

.trivyignore
build.gradle.kts

- uplift to latest hmpps.gradle-spring-boot plugin

PUD-208: Ignore trivy warning whilst DPS_tech_team find a fix for security issues with spring 5.5.1

---

src/main/resources/logback-spring.xml

The intention here is to:
- make sure all the logs are sent to both appenders (except for the App Insights logs which aren't relevant for appender 1)
- simplify the logback configuration

NJ Ensure all logs are sent to both loggers

---

src/main/resources/db/migration/V6__Make_document_category_varchar_not_enum.sql

PUD-329: Change SQL type of category column.  Only tested/testable by local running of actual app.  (Also, leaves the SQL ENUM type recall_document_category in existence but un-used).

PUD-329: Bug: persistence as ENUM not working versus actual Postgres DB but passes build test

---

build.gradle.kts

In order to ensure that spring-security-core is on v5.5.1 (which contains the vulnerability fix reported by the security pipeline)

PUD-426 Upgrade HMPPS Spring-boot gradle plugin to 3.3.6

---

helm_deploy/manage-recalls-api/values.yaml
src/main/resources/application.yml

This removes the DSN configuration in local development so we don't spam
sentry with errors.

Disable sentry in local development

---

Dockerfile

This will allow us to match up errors to reported releases.
ref PUD-601

Set the SENTRY_RELEASE env variable

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/RecallRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt

The idea of /search on Recall is a flexible future query.  
Switching to findByNomsNumber for now - given issues using QueryByExample with non-nullable properties of data class.

PUD-610  Reduce risk of a duplicate booking BE - query with findByNomsNumber

---

scripts/rerun-circleci-job.sh

So it turns out there is an API that enables you to re-run an already
successful CircleCI job, but there is no UI for it.
ref: https://circleci.canny.io/cloud-feature-requests/p/re-run-successful-jobs-in-a-workflow

PUD-703: Add a script to re-run a completed CI job

---

helm_deploy/manage-recalls-api/Chart.yaml
helm_deploy/manage-recalls-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

ref: https://mojdt.slack.com/archives/CH6D099DF/p1633679858013800
This bump in the `generic-service` template adds in the needed
annotations requested by the cloud platform team. When the time comes to
move our apps onto the new "live" cluster the `contextColor` directive
will allow us to switch traffic (but it doesn't impact deployment,
that's another story).

Add in the needed ingress annotations for cluster migration.

---

.circleci/config.yml

Before I go full on self-hosting the Trivy database, try to see if the
"light" variant is more reliable (as it's a lot smaller to download).
ref: https://aquasecurity.github.io/trivy/v0.20.0/vulnerability/examples/db/#lightweight-db

Tell Trivy to use the "light" database

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/ResourceServerConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/BankHolidayHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/ClamAVHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/CourtRegisterHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/GotenbergHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/HmppsAuthHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/PingHealthCheck.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/PrisonRegisterHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/PrisonerOffenderSearchHealth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/S3Health.kt
src/main/resources/application.yml

TODO: Expose the metrics to prometheus once I've confirmed the http request timing is appropriate on the cluster.

PUD-816: Enable prometheus metrics and include upstream health metrics

---

src/main/resources/application.yml

The documentation is unclear as to whether they're all enabled by default or not...

Explicitly enable the metrics endpoints

---

.trivyignore
build.gradle.kts
owasp.suppression.xml

Added OWASP suppression until 1 December, possibly a new version will be released by then.

Add suppression for OWASP failure. Thymeleaf isnt exposed to API, just used in transition to PDF.

---

helm_deploy/manage-recalls-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

The app crashes out with an invalid DSN, but starts up fine if none is
present.

Only set the SENTRY_DSN in pre-prod and prod

---

.circleci/config.yml
helm_deploy/values-manage-recalls-dev.yaml
helm_deploy/values-manage-recalls-preprod.yaml
helm_deploy/values-manage-recalls-prod.yaml

It looks like the YAML merge didn't go well, so I've just duplicated the
content from the `values-<env>.yaml` files into the new manage-recalls
ones.
Will clean this up as I go (and close of the deployments in
`ppud-replacement-<env>`.

Fix the YAML merge in helm

---

helm_deploy/manage-recalls-api/Chart.yaml

This fixes some issues with the grafana dashboards not loading
ref PUD-1129

Update the prometheus-alerts helm chart

---

.trivyignore

CVE-2021-44228: New on 10/Dec/21 in org.apache.logging.log4j:log4j-api 2.14.1 : ignore pending determining inclusion path

CVE-2021-44228: ignore for now

---

build.gradle.kts

PUD-1210  gradle-spring-boot plugin to 3.3.16; remove force of log4j2.version

PUD-1210  gradle-spring-boot plugin to 3.3.16: netty and log4j CVEs

---

build.gradle.kts

TECH: logback.version to 1.2.9 for CVE-2021-42550
Passes `./gradlew dependencyCheckAnalyze --info` which is logged task for failing circle "Security" job  `hmpps/gradle_owasp_dependency_check`
Same job fails locally before this change, though this doesn't explain apparent repetition of same failure for `legacy-ppud-api`: https://mojdt.slack.com/archives/C0223AGGQU8/p1640281055036100?thread_ts=1640236006.020200&cid=C0223AGGQU8

TECH: logback.version to 1.2.9 for CVE-2021-42550

---

.circleci/config.yml

This will send a notification to `#ppud-replacement-dev` on a failure in
any of the `build-test-and-deploy` jobs.

PUD-1262: Notify slack on workflow failure.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/MissingDocumentsRecordComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt

PUD-1259  missing documents records BE: remove transitional API code now that UI change is complete
FYI I'm still looking at improving the PACT in this area, e.g. given that the UI contract "expected" `emailFileName` in the MDR when it for certain was not present.

PUD-1259  missing documents records BE: remove transitional API code

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DocumentService.kt
src/main/resources/db/migration/V68__Non_blank_details_for_document_version_gt_one.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/DocumentComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/MissingDocumentsRecordComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/DocumentRepositoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/MissingDocumentsRecordRepositoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/random/RandomUtilities.kt

API: require generated document detail to be non-blank for all document versions except the first, version 1

PUD-1282  API: document detail to be non-blank for version gt 1

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/RestConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/SpringFoxConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/LastKnownAddress.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/LastKnownAddressRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/domain/domain.kt
src/main/resources/db/migration/V73__Add_last_known_addresses_table.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ComponentTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/LastKnownAddressComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/LastKnownAddressRepositoryIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/random/RandomUtilities.kt

PUD-1319  API: Support saving and return of offender last known addresses versus Recalls
To follow: PACT uplift to test LastKnownAddresses on Recall response.

PUD-1319  API: Support last known addresses

---

src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt

PUD-1360  PACT: ensure coverage is in place for non-empty list of lastKnownAddresses: API

PUD-1360  PACT: coverage for non-empty list of lastKnownAddresses

---

helm_deploy/manage-recalls-api/subcharts/gotenberg/templates/deployment.yaml

This increases the default requests for CPU/RAM in gotenberg from:
- CPU: 10m -> 50m
- RAM: 100Mi -> 200Mi
The limits remain the same as before.

Set resource requests for Gotenberg.

---

build.gradle.kts
helm_deploy/manage-recalls-api/Chart.yaml

TECH: remove all forced versions for OWASP/CVEs plus minor uplifts - read-back from recent changes in `legacy-ppud-api`.  Passes local "./gradlew dependencyCheckAnalyze".

TECH: remove all forced versions for OWASP/CVEs plus minor uplifts

---

README.md

One word PR: missed link update.
Note: the URL for our API swagger has changed - slightly.
This fix should also propagate to Structurizr.

PUD-1486  BE: Missed API 'badge' link update

---

.gitignore
Dockerfile
helm_deploy/manage-recalls-api/Chart.yaml
helm_deploy/manage-recalls-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/HealthController.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/health/HealthCheckComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/health/InfoComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/HealthControllerTest.kt

This hides away all the actuator endpoints (health, info, prometheus)
from public view and onto port 8081.
I've added in an extra `healthController` to allow external tests
(pingdom) to still check the health of the API.

PUD-1377: Switch the actuator endpoints onto a private port

---

helm_deploy/manage-recalls-api/templates/networkpolicy-ppud-replacement-ingess.yaml

This is so that the dashboards app can get the current version of the
application - this is now only available internally to the cluster.

Allow network ingress from the `manage-recalls-dev` namespace

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/HealthController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/HealthControllerTest.kt

This is just to make it consistent with everything else and to also make
it easier to test on the UI end.

Make the `/health` endpoint return JSON.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/HealthController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/HealthControllerTest.kt

This endpoint is used to report the version tested in the E2E tests so
it needs this info in it.

Add the version and buildUrl to external `/health`

---

helm_deploy/manage-recalls-api/templates/dashboards.yaml
helm_deploy/values-dev.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallServiceParameterisedTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallServiceTest.kt

The lazy initialisation of the counter wasn't giving us a default zero
counter on application load, this change fixes that.

Initialise the rtcCounter on start

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/BankHolidayRegisterClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/CourtRegisterClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/ErrorHandlingClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/PoliceUkApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/PrisonRegisterClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/ClamAVHealthTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/CourtRegisterIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/PrisonRegisterIntegrationTest.kt

This adds prometheus metrics for timeouts calling upstream services.

PUD-1197: Add metrics for timeout errors

---

helm_deploy/manage-recalls-api/values.yaml

We've now got them tracked on the dashboard...

PUD-1524: Ignore ClientTimeoutException's in Sentry

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/search/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/search/PrisonerOffenderSearchClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/SearchComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/SearchControllerTest.kt

Along with PUD-1577, I'm wondering, whether we should move to greater shared code for webClient interaction also considering our current separation of `ErrorHandlingClient` and `AuthenticatingRestClient`.

PUD-1578 API person search to return 404 if no results, rather than 500

---

.circleci/config.yml

ref: https://mojdt.slack.com/archives/C69NWE339/p1646998111225519
It looks like there is a gradle caching issue since updating the HMPPS
gradle-spring-boot-plugin on this task.  This should get it working
again.

Fix the owasp dependency check

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallNotificationComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/LastKnownAddressComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/MissingDocumentsRecordComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/RecallNotificationGotenbergComponentTest.kt

PUD-1366 Remove un-used alternate end-points from Back End, i.e. removal of old end-points for /missing-documents-records and /last-known-addresses

PUD-1366 Remove un-used alternate end-points from Back End

---

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/DocumentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RescindRecordController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/DocumentComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/NoteComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/RescindRecordComponentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/DocumentControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RescindRecordControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RescindRecordServiceTest.kt

PUD-1679 Slice 1 of remove <ResponseEntity<T>> return types in Controllers
Code clean-up: let's agree if this is good before doing much more of the same.

PUD-1679 Slice 1 of remove <ResponseEntity<T>> return types

---

build.gradle.kts
gradle.properties

Found a set of JVM configuration allowing all compile steps to pass - and eventually also how to have them applied successfully for local and all our CI builds.

PUD-1705  API build fails on Kotlin 1.6.20 (hmpps plugin > 4.1.3): compileTestKotlin StackOverflowError!
