ministryofjustice/manage-recalls-api

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/SearchController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/SearchControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/PrisonerSearchIntegrationTest.kt
PUD-217: API: Add gender etc. to offender properties returned by prisoner /search
=> PUD-217: API: Add gender etc. to offender properties returned by search

build.gradle.kts, src/main/resources/logback-spring.xml
So that the logs can be indexed correctly in Elasticsearch and
thus can be filtered appropriately in Kibana
=> NJ Append console logs in Logstash format

build.gradle.kts, src/main/resources/logback-spring.xml
- Revert "NJ Fix deployment"
- Revert "NJ Append console logs in Logstash format (#70)"
=> NJ Revert appender 1 encoder change

README.md, pact/README.md, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/pact/provider/ManageRecallsUIPactTest.kt
Should allow https://github.com/ministryofjustice/manage-recalls-ui/pull/78 to pass PACT Verification.
=> PUD-340: API: PACT test for getRecall

src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/pact/provider/ManageRecallsUIPactTest.kt
PUD-86: Support PACTs from UI for update variants.
We certainly need to better understand what makes for effective use of PACT - from both the API and I think the UI side.
For now this branch satisfies the requirements of https://github.com/ministryofjustice/manage-recalls-ui/tree/PUD-86-assess-decision-fix
=> PUD-86: Support PACTs from UI for update variants

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/main/resources/db/migration/V8__Add_recall_email_received_datetime.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/RecallsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/UpdateRecallIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/pact/provider/ManageRecallsUIPactTest.kt
PUD-355 API - get and update (patch) recallEmailReceivedDateTime
=> PUD-355 API - get and update (patch) recallEmailReceivedDateTime

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/ThymeleafConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/RecallDocument.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RevocationOrderService.kt, src/main/resources/db/migration/V13__Rename_recall_columns.sql, src/main/resources/db/migration/V14__Add_recall_sentencing_columns.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/RecallsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RevocationOrderServiceTest.kt
- cleanup unnecessary Column annotations
=> PUD-247: Add sentencing info fields

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/LocaleConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/RecallsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt
- Set locale for app as UTC
- Use OffsetDateTime rather than ZonedDateTime
=> PUD-434: Fix datetime format to be in UTC.

src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/UpdateRecallComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt
Bit of a no-op, unless I've missed something.
=> PUD-475: Reduce chance of error in entering releasing prison - back end

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsControllerTest.kt
PUD-508  Add get dossier end-point on BE to return a PDF - just the RecallNotification as a place-holder for now
=> PUD-508  Add get dossier end-point on BE to return a PDF

src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt
@mikedunfordEE PACT passes with this versus your UI branch as per https://mojdt.slack.com/archives/C0223AGGQU8/p1630937274024200?thread_ts=1630670239.071500&cid=C0223AGGQU8
=> PUD-508 satisfy PACT

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DossierService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/TestFixtures.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DossierServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RevocationOrderServiceTest.kt
This is only a small and intermediate step but includes some test changes: PR in case contentious and to review as small changes.  @mikedunfordEE ?
=> PUD-521 introduce dossierService; minor changes to existing service test

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallDocumentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/TestFixtures.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallDocumentServiceTest.kt
Introduce documentService getDocumentWithCategory; modify some existing tests for class
=> PUD-521  Introduce documentService getDocumentWithCategory

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/RecallRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/SearchRecallsComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DossierServiceTest.kt
Scaleable query implementation to follow.
=> PUD-610  Reduce risk of a duplicate booking BE - filter implementation

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/RecallRepository.kt, src/main/resources/db/migration/V35__Add_booked_by_user_id_to_recall.sql, src/main/resources/templates/recall-summary.html, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ComponentTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallServiceTest.kt, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallSummaryHtmlGenerationTest_generate recall summary HTML.approved
=> PUD-181: Who booked a recall

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UpdateRecallServiceTest.kt
Either instead of this or right after the cleaner solution is PUD-649 so will likely play that after lunch.
=> PUD-640  Add the probation local delivery unit - BE: allow probatioDivision to be optional

.circleci/config.yml
They don't need to run in serial right?
=> Run the doc tests alongside the other tests

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt
Yes it's ugly and verbose but it should tell us if this issue is on the BE in any way.
=> PUD-616  temporary logging for local delivery unit issue

.trivyignore
This would unblock all the other PRs...
=> Ignore netty CVEs for now

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt
=> PUD-616 delete temp logging

.gitignore, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/PdfDocumentGenerationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/LetterToProbationGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/LetterToProbationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallImage.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallSummaryGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallSummaryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/TableOfContentsGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/TableOfContentsService.kt, src/main/resources/templates/table-of-contents.html, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/CreateDossierComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallNotificationComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/DocumentMatchers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/GotenbergMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DossierServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallNotificationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallSummaryGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RevocationOrderGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/TableOfContentsGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/TableOfContentsServiceTest.kt, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/service/TableOfContentsHtmlGeneratorTest_generate revocation order HTML.approved
=> PUD-165: Improve HTML

.trivyignore, build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/TableOfContentsGeneratorTest.kt
This fixes all the currently ignored CVEs so I've removed the `.trivyignore` file.
=> Update `uk.gov.justice.hmpps.gradle-spring-boot` to 3.9.9

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReasonsForRecallGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReasonsForRecallService.kt, src/main/resources/templates/reasons-for-recall.html, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReasonsForRecallGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReasonsForRecallHtmlGenerationTest.kt, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReasonsForRecallHtmlGenerationTest_generate HTML.approved
=> PUD-159  Include reasons for recall document - create document

RUNBOOK.md
I'll add a section to the end of this in a bit that the alertmanager alerts can link to with better descriptions of the issues and how to follow them up
=> PUD-658 Add a runbook

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallsController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallResponseTest.kt
PUD-720  BE: return status DOSSIER_CREATED when dossierCreatedByUserId is not null
=> PUD-720  BE: add status DOSSIER_CREATED

.circleci/config.yml
The cache code is now in the HMPPS Orb
=> Revert "PUD-795: Stabilise the Trivy scans"

build.gradle.kts, src/main/resources/application.yml
Also try updating the actuator and micrometer deps... See if this helps.
=> Try spaces in between the endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/ClamAVHealth.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/PingHealthCheck.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/health/S3Health.kt
It wasn't matching the one in UI :facepalm:
=> Rename the `upstream_health` metric

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/SpringFoxConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/DocumentController.kt
- Add error response to add document endpoint
=> PUD-915: Fix swagger for mono responses

scripts/complete-recalls.sql, src/main/resources/application.yml
- Increase prisoner search timeout
=> PUD-964: Add script for cleaning up open recalls in dev/preprod.

.circleci/config.yml
- Run against consumer(UI) branch via webhooks
- Run only against 'main' for PR builds
- Run against main/preprod/prod for main builds
=> Break out PACT jobs:

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/SpringFoxConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/PoliceUkApiClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ReferenceDataComponentTest.kt
- use Api package; fix swagger
=> PUD-1030  police force select from list BE delta

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallService.kt, src/main/resources/db/migration/V58__Restrict_names_columns.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/UpdateRecallComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/random/RandomUtilitiesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallServiceTest.kt
=> PUD-1007: Restrict database to ensure first & last names are not null now migration has been performed

scripts/copy-database.sh, scripts/port-forward-db.sh, scripts/port-forward-http-proxy.sh
=> Add a script for copying the database to the new environment

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/DocumentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/UserController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallNotificationComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/DossierGenerationGotenbergComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/RecallNotificationGotenbergComponentTest.kt
=> PUD-1120: Remove superfluous endpoint

RUNBOOK.md, scripts/copy-database.sh, scripts/copy-s3-bucket.sh, scripts/flush-env.sh, scripts/getAccessToken.sh, scripts/port-forward-db.sh, scripts/port-forward-http-proxy.sh
=> Remove all references to the `ppud-replacement-<env>` namespaces.

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/dossier/DossierContextFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/register/PrisonRegisterClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/PrisonLookupService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/PrisonValidationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ReferenceDataComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/dossier/DossierContextFactoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/dossier/DossierContextTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/DossierGenerationGotenbergComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/GotenbergComponentTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/RecallNotificationGotenbergComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/PrisonRegisterIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/PrisonRegisterMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/PrisonLookupServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/PrisonValidationServiceTest.kt
PUD-1060  Include Welsh recall leaflet for Welsh prisons
=> PUD-1060  Include Welsh recall leaflet for Welsh prisons

.trivyignore, build.gradle.kts
PUD-1192  Update gradle-spring-boot plugin and log4j for CVEs x2
=> PUD-1192  Update gradle-spring-boot plugin and log4j for CVEs x2

src/main/resources/templates/letter-to-prison_confirmation-of-rar.html, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/lettertoprison/LetterToPrisonConfirmationHtmlGenerationTest_generate fully populated HTML.approved
=> PUD-858: Improve format for Part 1 form in Letter to Prison

.circleci/config.yml, .tool-versions, Dockerfile, build.gradle.kts, ci-docker-tests/Dockerfile, gradle.properties
PUD-1237  Update manage-recalls-api to JDK17 (openjdk:17)
=> PUD-1237  Update manage-recalls-api to JDK17 (openjdk:17)

README.md
TECH README re. service limitations re. https://mojdt.slack.com/archives/C0223AGGQU8/p1638441091153400
=> TECH README re. service limitations

scripts/getClientToken.sh
TECH-getClientToken-script: shareable version of https://mojdt.slack.…com/archives/C0223AGGQU8/p1640169321014000?thread_ts=1639646984.407700&cid=C0223AGGQU8
=> TECH-getClientToken-script

build.gradle.kts, owasp.suppression.xml
- force uplift log4j to 2.17.1
- force uplift thymeleaf to 3.0.14.RELEASE
=> Fix OWASP failures.

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DocumentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/MissingDocumentsRecordComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallControllerTest.kt
PUD-1260  Add emailFileName property missing documents response
Might be ready; I haven't reviewed the changes myself yet really.
=> PUD-1260  Add emailFileName property missing documents response

helm_deploy/manage-recalls-api/values.yaml, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ReferenceDataComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/CourtRegisterIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/mockservers/CourtRegisterMockServer.kt
PUD-1268  Add missing document record tests to PACT: API side, needs to precede UI side change.
=> PUD-1268  Add missing document record tests to PACT

.circleci/config.yml, scripts/run-e2e-tests.sh
This will ensure that only one 'deploy_only' workflow at a time runs...
=> PUD-1285: Stop parallel E2E test runs

src/main/resources/db/migration/V68__Non_blank_details_for_document_version_gt_one.sql
Should fix up existing data for included new DB constraints as per promote issue per Slack: https://mojdt.slack.com/archives/C0223AGGQU8/p1642415970177700?thread_ts=1642414658.172800&cid=C0223AGGQU8
=> PUD-1282  Fix up existing data prior to constraint application

src/main/resources/db/migration/V70__Correct_in_custody_boolean_data_migration.sql
See e.g. Slack: https://mojdt.slack.com/archives/C0223AGGQU8/p1642681479272600
=> PUD-1333  Correct `in_custody` data migration

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/DomainConverters.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/LastKnownAddressRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/DocumentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/DocumentComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/LastKnownAddressComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/MissingDocumentsRecordComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/LastKnownAddressControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/MissingDocumentsRecordControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/LastKnownAddressRepositoryIntegrationTest.kt
- add support for /recalls/{recallId}/* for MissingDocumentsRecords & LastKnownAddresses
=> PUD-1281: Delete a last known address.

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/OffenderNotificationGenerator.kt, src/main/resources/templates/letter-to-probation.html, src/main/resources/templates/offender-notification.html, src/main/resources/templates/reasons-for-recall.html, src/main/resources/templates/recall-summary.html, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/dossier/ReasonsForRecallHtmlGenerationTest_generate HTML.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/LetterToProbationHtmlGenerationTest_generate HTML.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/OffenderNotificationHtmlGenerationTest_generate offender notification HTML.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallSummaryHtmlGenerationTest_generate recall summary HTML.approved
=> PUD-708: Add missing logo

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt
TECH: Address some Recall and RecallController JPA related warnings plus remove unused code
=> TECH: Address some Recall and RecallController JPA related warnings

scripts/getClientToken.sh, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/RestConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/SpringFoxConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Converters.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/domain/domain.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallService.kt, src/main/resources/db/migration/V74__Add_warrant_reference_number.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/domain/DomainTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/RecallServiceTest.kt
PUD-1398  BE: Store and update new warrant reference number property on Recall
=> PUD-1398 warrantReferenceNumber String property

scripts/delete-recalls.sql, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallNotificationContextFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallSummaryGenerator.kt, src/main/resources/templates/recall-summary.html, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/DocumentComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GenerateDossierComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallNotificationComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallNotificationContextFactoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallSummaryGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallSummaryHtmlGenerationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/GotenbergComponentTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/RecallNotificationGotenbergComponentTest.kt, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallSummaryHtmlGenerationTest_generate in custody recall summary HTML.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallSummaryHtmlGenerationTest_generate not in custody recall summary HTML.approved
- include delete recall tidy up helper script
=> PUD-715: Remove current prison and add last known addresses for NiC recall summary.

RUNBOOK.md
Fixed a broken link and removed a left over comment from the template.
=> Fix the runbook.

.circleci/config.yml, docker-compose.yml
Using `latest` probably isn't the best thing (as it's a moving target), so let's see if this resolves the CircleCI issues...
=> Use a specific release of minio

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/LetterToProbationGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallNotificationContextFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallNotificationComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/LetterToProbationHtmlGenerationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/RecallNotificationContextTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/documents/RecallNotificationGotenbergComponentTest.kt, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/LetterToProbationHtmlGenerationTest_generate in custody letter to probation HTML.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/recallnotification/LetterToProbationHtmlGenerationTest_generate not in custody letter to probation HTML.approved
PUD-710 & PUD-717: NIC assessment: Letter to probation variation
=> PUD-710 & PUD-717: NIC assessment: Letter to probation variation

.circleci/config.yml, scripts/run-e2e-tests.sh
I have a PR for the HMPPS orb open, but god knows when it'll get picked
up... This will make things more stable for now...
=> Workaround for the E2E triggers timing out.

src/main/resources/templates/letter-to-prison_custody-office.html, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/lettertoprison/LetterToPrisonCustodyOfficeHtmlGenerationTest_generate fully populated HTML FTR 14 days.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/lettertoprison/LetterToPrisonCustodyOfficeHtmlGenerationTest_generate fully populated HTML FTR 28 days.approved, src/test/resources/uk/gov/justice/digital/hmpps/managerecallsapi/documents/lettertoprison/LetterToPrisonCustodyOfficeHtmlGenerationTest_generate html when no additional license conditions FTR 14 days.approved
=> PUD-757: Tidy up typo and line breaks

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/UserDetailsService.kt, src/main/resources/db/migration/V79__Add_document_index.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/DocumentComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/GetRecallsComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/RecallControllerTest.kt
- Add user details cache
- Lookup emailfileName for MDR for docs collection rather than db.
=> PUD-1447: Use RecallLite for get recalls to improve performance

helm_deploy/manage-recalls-api/templates/networkpolicy-ppud-replacement-ingess.yaml
The component label was not present.
=> Update the label used in the networkpolicy

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/resources/db/migration/V86__Add_rescind_record_recall_id_index.sql
- add index to improve slow rescind lookup by recallid
=> PUD-712: Add RTC thresholds for dev & preprod (set prod explicitly to 0 to ensure immediate RTC checks)

src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt
PUD-1488  API: Add note BE: needed PACT tweaks
=> PUD-1488  API: Add note BE: needed PACT tweaks

helm_deploy/manage-recalls-api/templates/dashboards.yaml
Gives something like this per upstream:
=> PUD-1523: First pass at a dashboard for upstream requests

helm_deploy/manage-recalls-api/templates/dashboards.yaml
- fix missing data issue
- add an overall latency chart (per upstream)
i.e.
=> Updates to the upstream HTTP reqs dashboard

helm_deploy/manage-recalls-api/templates/dashboards.yaml
- Number of pods running
- HTTP request rate
- Automated RTC changes
=> Add some extra graphs to the dashboard

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/AuthenticatedWebClientConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/search/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/search/PrisonerOffenderSearchClient.kt
I missed these when doing the registers the other day... There are no (unit) tests on these clients, I'm happy to add some, but not really sure where to start - anyone for pairing?
=> Add timeout counters for the "search" clients

helm_deploy/manage-recalls-api/values.yaml
Reverts ministryofjustice/manage-recalls-api#545
=> Revert "It looks like I labelled ClientTimeoutException wrong..."

src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/config/OpenApiConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/PartBRecordController.kt
Missed this: https://mojdt.slack.com/archives/C0223AGGQU8/p1648043591354899
=> PUD-1598  Flatten PartBRecordId for swagger

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/PartBRecordService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/PartBRecordComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/PartBRecordServiceTest.kt
I've not yet looked into any test to prove that this processes the files in parallel ...
=> PUD-1612  Call clamav in parallel for multiple uploaded documents

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/Recall.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/db/RecallRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/documents/DocumentFormatters.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReportsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/AuthenticatedClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ComponentTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/EndpointSecurityComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/ReportsComponentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/component/pact/provider/ManageRecallsUIPactTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/integration/db/RecallRepositoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/managerecallsapi/service/ReportsServiceTest.kt
PUD-1654  Weekly recalls new report Back end: initial thread.
=> PUD-1654  Weekly recalls new report Back end: initial thread.

build.gradle.kts
Should clear OWASP/security job for API - until the next new CVE.
=> TECH plugin-> 4.1.6 for CVE-2022-0272

Dockerfile
PUD-1704  Tech API server class GC etc.
Perf related running service config (GC) change: see JIRA for links/context.
=> PUD-1704  Tech API server class GC etc.
